/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chakrapa' at '3/15/17 10:12 AM' with Gradle 2.14.1
 *
 * @author chakrapa, @date 3/15/17 10:12 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }   
}  
