/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chakrapa' at '3/3/17 9:22 PM' with Gradle 2.14.1
 *
 * @author chakrapa, @date 3/3/17 9:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
